# 配置文件请严格遵循 yaml 语法格式，yaml 学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# 是否强制切换微信号 （2019年9月27日15:31:22 最近保存最近登录状态出错，所以此设置无效，每次登录得重新扫码。）
is_forced_switch: False

#---------------------------------------自动回复功能设置--------------------------------------start


#---------------------------------------自动回复功能设置--------------------------------------end



#---------------------------------------定时提醒功能设置--------------------------------------start
alarm_info:
  #True 开启定时提醒，False 关闭
  is_alarm: True

  girlfriend_infos:
    #女友微信昵称或者备注名，不能输入微信号。（如填：文件传输助手，发消息到文件传输助手，测试效果）
    - wechat_name:
        - 'Dear~'
      alarm_timed: # 定时发送的时间
        - "6:00"
      alarm_jitter: 300 # 给定时时间加一个随机抖动 300 秒。定时时间【-5，+5】分钟范围内发送。（不然每天固定在同个时间段有点尴尬）（可空）
      is_tomorrow: True # 是否发送明日信息（如天气，星座，万年历）
      #女友所在城市，用于发送天气。（可空）
      city_name: '茂名'
      # 此城市的 pm2.5 值。
      air_quality_city: '茂名'
      # 格言渠道（1 : ONE●一个，2 : 词霸（每日英语，双语）3: 土味情话 4 : 一言，5：笑话，6 民国情书,7彩虹屁)(可空)
      dictum_channel: 2
      # 从哪天开始勾搭的（可空），配合 start_date_msg 使用。
      start_date: '2020-8-6'
      # 自定义方案（可空）， {}表示用于占位，代表天数，与 start_date 一起使用。单填无意义
      #  默认为：『宝贝这是我们在一起的第{}天』,参考：爱你的第{}天
      start_date_msg: '宝贝这是我们在一起的第{}天'
      # 万历年（可空），（中老年最爱）
      calendar: False
      # 星座运势（可空）填生日日期："1980-06-15" or "06-15" or "白羊座"
      horescope: "天蝎座"
      # 落款（可空），落款参考：['厌物', '你脚下的蚂蚁', '专说骗人的诳话者', '黄天霸', 'cxk', '魔鬼的叔父', '哺乳类脊椎动物之一', '名字写在水上的人', 'BIG BAD WOLF', '你的兄弟']
      sweet_words: '你脚下的蚂蚁'



#---------------------------------------定时提醒功能设置--------------------------------------end




#--------------------------- 群聊助手设置 --------------------------end


# start ----------------------------------- 数据库设置 ----------------------------------- start
# 可不安装与设置数据库内容，数据库主要用于群助手功能中，查询数据的缓存。
db_config: # 请安装 mongodb 数据库
  is_open_db: True # 是否开启数据库功能
  mongodb_conf:
    'host': 'localhost'
    'port': 27017
#   end ----------------------------------- 数据库设置 ----------------------------------- end